practical-tutorials/project-based-learning

README.md
Added 2 tutorials on Go lang:
1. Build web apps with Gin framework
2. BDD with Godog
=> Add more go tutorials

README.md
=> Fix typo in JavaScript section

README.md
This is awesome! I noticed that there weren't too many Angular resources, so this PR adds a two part series of building a progressive Hacker News client using Angular 2+ :)
=> add angular2+ hacker news tutorial

README.md
Updated list with a tutorial on how to create a telegram bot using Python
=> Added Telegram bot creation tutorial

README.md
- https://github.com/write-you-a-scheme-v2/scheme
- https://www.wespiser.com/writings/wyas/home.html
This is the upgraded version of the original write yourself a scheme in 48 hours, in a modern Haskell way.
=> add haskell project write-you-a-scheme-v2

README.md
The old link was giving a 404 error
=> React music player part 3 - fixed broken link

README.md
Hey @tuvttran 
I've added the lessions for SilverStripe (a PHP CMS) in. contains a full website build for a real estate website example. Also add the ":" after PHP.
Peter
=> Adding SilverStripe example in

README.md
Splitted Telegram tutorial to two parts
=> Updated Python Bot Telegram tutorials

README.md
http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/
=> Added Python Deep Learning

README.md
Add a new section for the [Lua ](https://www.lua.org/) programming language and a new section for the [LÖVE](https://love2d.org/) 2D game engine. Inside it add a tutorial for creation of a complete 2D game with **Lua** and **LÖVE** called [BYTEPATH ](http://store.steampowered.com/app/760330/BYTEPATH/) by [SSYGEN](https://github.com/SSYGEN).
=> Add BYTEPATH tutorial

README.md
Add "Rust in Detail: Writing Scalable Chat Service from Scratch" tutorial by [Nikita Baksalyar](https://github.com/nbaksalyar).
=> Add Rust tutorial about writing a chat service.

README.md
Separate additional subsection in C/C++ section about OpenGL and move there the tutorial related to creating Minecraft game clone. Also add tutorial about creating of a complete 2D Breakout game clone, part of [Joey de Vries](https://github.com/JoeyDeVries)'s [Learn OpenGL](https://learnopengl.com/) tutorial.
=> Add tutorial about creating Breakout game clone

README.md
Full title: "Vue 2 + Firebase: How to build a Vue app with Firebase authentication system in 15 minutes"
=> Javascript: "Vue 2 + Firebase Authentication App"

README.md
* Add link to the official site of the Handmade Hero video game creation video tutorial series to the C++ OpenGL subsection.
* Sort C++ OpenGL subsection tutorials alphabetically.
=> Add Handmade Hero tutorial.

README.md
Add series of articles about writing a Space Invaders game clone by Nick Tasios.
=> Add tutorial about writing a Space Invaders game

README.md
Add tutorial about writing a Tetris game by Javier López.
=> Add Tetris tutorial

README.md
Add tutorial about writing of a high performance matrix multiplication in C++ by Jean Guegant.
=> Add a matrix multiplication tutorial

README.md
* Add additional sub-section in C/C++ section about network programming.
* Move "Let's Code a TCP/IP Stack" tutorial series in it.
* Add series of tutorials about writing concurrent servers by [Eli Bendersky](https://github.com/eliben).
=> Add tutorial about writing concurrent servers.

README.md
Added a tutorial on making ToDo App with Angular 5. Also updated descriptions of some Angular links.
=> Added a tutorial on making ToDo App with Angular 5. Also updated descriptions of some Angular links.

README.md
These are the links to a three parts tutorial series on implementing a search engine in Python.
=> Added 3 new links.

README.md
1.  Writing a minimal x86-64 JIT compiler in C++.
- Deleted part three because it gives 404 error (Page Not Found)
2.  Add video tag to youtube links.
=> Delete JIT tutorial (C++) and add video tags

README.md
Create a blog using Vue, GraphQL and Apollo
=> VueJS - blog tutorial

README.md
Hey @tuvtran ,
I've written 2 tutorial projects to help people get from beginner who understands syntax, to intermediate who can structure and complete large projects. I'd love to add them to your already excellent list. Thanks!
=> Python programming projects for advanced beginners

README.md
=> Add Erlang Tutorial

README.md
=> Removed unavailable link

README.md
How to create an OS from scratch : https://github.com/cfenollosa/os-tutorial
=> Add a C tutorial about creating an os

README.md
Any and all videos that feature some work on the CoreWiki project. This is a Wiki-style content management system that has been completely written in C# with ASP.NET Core and Razor Pages. You can find the source to this project at: https://github.com/csharpfritz/CoreWiki
=> Add "Building the CoreWiki" (C#)

README.md
Learn Ruby on Rails by building a Twitter clone.
=> Add The Ruby on Rails Tutorial

README.md
Intermixed seems to fit better than intermix.
=> Spellchecked README.md

README.md
Added Hack Club Workshops! 
Hack Club Workshops are a collection of workshops written by an international open-source student non-profit. It contains a series of guides and tutorials for students to start learning to build or to code via creating various projects.
=> Add Hack Club Workshops to additional resources

README.md
[Enlight](https://enlight.nyc/) is an awesome series of small projects written by a group of students. 
In the creator, @shamdasani's own words:
> A couple years ago, I started to learn web development. At first, I ended up taking many courses and reading books. However, I learned so many terms, objects, statements, etc. that I couldn’t really implement them. Then, I started to make mini-projects by following tutorials online and scraping through code on GitHub, and quite frankly, I learned a lot more than I would have doing anything else. I believe that the best way to learn is to create. Try, fail, and get back up again. Make something cool even if you don't 100% know what you are doing. Then, try and make it even better. Trust me, you’ll amaze yourself with what you'll build.
=> Add Enlight.nyc

README.md
Not sure what happened there, but my links submitted in previous PRs are duplicated for some reason.
=> Remove duplicate links

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Github Template Files that will enable Contributors Communicate Intentions Better
=> add Github Template Files that will enable Contributors Communicate Better

README.md
=> Added Deep Learning and Image Analysis Tutorials

README.md
There was a simple type in one of the links. The square brackets and round brackets were mistakenly interchanged. See below for screenshots.
Now the link works and it looks the way it's supposed to.
Before:
After:
=> Update README.md : Fix typo in markdown link

README.md
Few tiny* 3d graphics tutorials
4 lines in the readme.md
This change is required because graphics is cool! No fixes, just new content.
Extensive testing by thousands of people.
=> Tiny* 3D graphics projects

README.md
Added [The WebDev Coach](https://www.youtube.com/channel/UCERIxMohPPYmwjtHF3DdlJQ/videos?view_as=subscriber)'s Random Quote Machine tutorial.
It is a new tutorial.
=> Add The WebDev Coach's Random Quote Machine React tutorial

.travis.yml
=> Add awesome_bot to validate links via .travis.yml #113

README.md
Add tutorial about how to write your own git like source control system in Python by Thibault Polge.
=> Add tutorial about how to write your own git

README.md
The new updated link is https://os.phil-opp.com/
=> Fix OS tutorial in Rust

README.md
cc @tuvtran 
I've written a couple of new projects, would love to add them here. Thanks!
I viewed the rendered markdown and clicked on the links
- [x ] New Article (change which adds functionality)
- [x ] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have made checks to ensure URLs and other resources are valid
=> Add some new projects

README.md
Added a new scope to the Deep Learning Section. LSTM RNN - Long Short Term Memory, Recurrent Neural Network
- [x ] I have read the **CONTRIBUTING** document.
- [ x] I have made checks to ensure URLs and other resources are valid
=> Added a LSTM RNN Taylor Swift Lyrics Generator

README.md
I was going to add a good Elixir tutorial that uses Mnesia and Phoenix
I checked the links to make sure they linked to the proper pages
=> add Elixir project

README.md
Added a beginner-friendly Ruby tutorial - a step-by-step walkthrough on how to build a Rails application that lets users post information about sharks and their behavior.
=> Added beginner-friendly Ruby tutorial

README.md
I was going to add a good Angular 8 tutorial that uses firebase and several design components, but I noticed that the tutorial was included under the Angular 6 version. Since that entry was submitted, the tutorial has been updated to Angular 8 and a second edition has been released.
Issue #28 was addressed
I checked the links to make sure they linked to the proper pages
- [ x] Content Update (change which fixes an issue or updates an already existing submission)
- [ x] New Article (change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have made checks to ensure URLs and other resources are valid
=> update Angular tutorial to new version and add part 2 link

README.md
Todoist clone with React and Firebase
We're going to be creating the popular Todoist list application (https://todoist.com) from scratch using React (Custom Hooks, Context), Firebase & React Testing Library (unit & integration testing).
I think this will help lot of beginners like me. Also I am learning GitHub so want to contribute to community.
Thanks :)
=> Added Todoist clone under React category

README.md
=> Added React Native Application with Redux Thunk

README.md
Link was provided by [this guy](https://github.com/Epreuve)
=> Updated Broken Link

README.md
=> Added byterun

README.md
I found this project interesting and thought it needs to be listed in your Clojure section.
=> Add prototyping with Clojure book

README.md
- [ x] New Article (change which adds functionality)
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have made checks to ensure URLs and other resources are valid
=> added link for face detector using opencv

README.md
Add a tutorial about writing a Tetris game in ClojureScript.
=> Add a tutorial about writing a Tetris game

README.md
Added "Let's build a URL shortener in Go - with Gin & Redis" project
Found this project tutorial a week ago, and it's quality is really good.
I completed the project.
=> Added "Let's build a URL shortener in Go - with Gin & Redis"

README.md
Add a tutorial series demonstrating how to build a retro first-person shooter from scratch in Swift by Nick Lockwood.
=> Add a tutorial series about making a FPS

README.md
Add a tutorial about writing an NES emulator in a Rust programming language.
=> Add a tutorial about writing an NES emulator

README.md
Go category cleanup after bad merge(on my part).
=> Go category cleanup after bad merge

README.md
Added a new Go project.
The Go category doesn't have a similar tutorial.
I completed it.
=> added Go project - TCP Chat

README.md
=> added JavaScript project

README.md
i have solved the issue #342
added link to the project
=> JavaScript TDD Todo List App added 

README.md
Added a new Go project.
The Go category doesn't have a similar tutorial.
I completed it.
=> added new Go project - bittorrent client

README.md
=> Add a new c/c++ project
